server.port=9093


spring.application.name=gemini
spring.ai.model.chat=google-genai
spring.ai.google.genai.api-key=AIzaSyDVe06tK6EM4yldlCXCxk2gjcgdniLrkME
spring.ai.google.genai.chat.options.model=gemini-2.5-flash

spring.ai.google.genai.chat.options.temperature=0.4
spring.ai.google.genai.chat.options.max-output-tokens=2048
